styles:
  templates:
    layoutRootPath: 'EXT:cozy_backend/Resources/Private/Layouts/'
    partialRootPath: 'EXT:cozy_backend/Resources/Private/Partials/'
    templateRootPath: 'EXT:cozy_backend/Resources/Private/Templates/'

page:
  pageview:
    paths: 'EXT:cozy_backend/Resources/Private/PageView/'

  meta:
    viewport: 'width=device-width, initial-scale=1'
    robots: 'index,follow'
    apple-mobile-web-app-capable: 'no'
    compatible: 'IE=edge'

config:
  no_cache: '0'
  removeDefaultJS: '0'
  admPanel: '1'
  prefixLocalAnchors: 'all'
  headerComment: 'build by Nimmermaer'
  sendCacheHeaders: '1'

routes:
  -
    route: robots.txt
    type: staticText
    content: "User-agent: *\r\nDisallow: /typo3/\r\nDisallow: /typo3_src/\r\nAllow: /typo3/sysext/frontend/Resources/Public/*\r\n"
  -
    route: favicon.ico
    type: asset
    asset: 'EXT:cozy_backend/Resources/Public/Icons/favicon.ico'
  -
    route: favicon-32x32.png
    type: asset
    asset: 'EXT:packages/cozy_backend/Resources/Public/Icons/favicon-32x32.png'
  -
    route: favicon-194x194.png
    type: asset
    asset: 'EXT:cozy_backend/Resources/Public/Icons/favicon-194x194.png'
  -
    route: favicon-36x36.png
    type: asset
    asset: 'EXT:cozy_backend/Resources/Public/Icons/android-chrome-36x36.png'
  -
    route: favicon-48x48.png
    type: asset
    asset: 'EXT:cozy_backend/Resources/Public/Icons/android-chrome-48x48.png'
  -
    route: apple-touch-icon.png
    type: asset
    asset: 'packages/cozy_backend/Resources/Public/Icons/android-chrome-72x72.png'
  -
    route: web-app-manifest-192x192.png
    type: asset
    asset: 'packages/cozy_backend/Resources/Public/Icons/android-chrome-192x192.png'
  -
    route: web-app-manifest-256x256.png
    type: asset
    asset: 'packages/cozy_backend/Resources/Public/Icons/android-chrome-256x256.png'
  -
    route: web-app-manifest-384x384.png
    type: asset
    asset: 'packages/cozy_backend/Resources/Public/Icons/android-chrome-384x384.png'
  -
    route: web-app-manifest-512x512.png
    type: asset
    asset: 'packages/cozy_backend/Resources/Public/Icons/android-chrome-512x512.png'