categories:
  CozyBackend: ~
  CozyBackend.defaults.paths:
    parent: CozyBackend
  CozyBackend.defaults.tt_content:
    parent: CozyBackend
  CozyBackend.defaults.pages:
    parent: CozyBackend
  CozyBackend.templates:
    parent: CozyBackend
  CozyBackend.meta:
    parent: CozyBackend
  CozyBackend.webmanifest:
    parent: CozyBackend
settings:
  componentsPath:
    category: CozyBackend.defaults.paths
    description: 'Paths für components'
    type: string
    default: 'Resources/Private/Components/'
  backendPath:
    category: CozyBackend.defaults.paths
    description: 'Paths für Backend components'
    type: string
    default: 'mblunck/cozy-backend:Resources/Private/Backend/'
  designTokens:
    category: CozyBackend.defaults.paths
    description: 'Paths für designTokens'
    type: string
    default: 'Tokens/designTokens.json'
  tt_content.default.header:
    category: CozyBackend.defaults.tt_content
    description: 'Overrides default text'
    type: string
    default: 'Hier ist ein Headertext'
  pages.default.abstract:
    category: CozyBackend.defaults.pages
    type: string
    default: 'Hier kommt ein Abstrakt'
  pages.browser.color:
    category: CozyBackend.defaults.pages
    type: color
    default: '#FF8700'
  page.webmanifest.name:
    type: string
    default: 'Cozy Backend'
    category: CozyBackend.webmanifest
  page.webmanifest.short_name:
    type: string
    default: 'CozyB'
    category: CozyBackend.webmanifest
  page.webmanifest.icons.file.prefix:
    type: string
    default: 'android-chrome-'
    category: CozyBackend.webmanifest
  page.webmanifest.theme_color:
    type: color
    default: '#ffffff'
    category: CozyBackend.webmanifest
  page.webmanifest.background_color:
    type: color
    default: '#ffffff'
    category: CozyBackend.webmanifest
